# Generated by Django 2.1.7 on 2019-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('designation', models.CharField(blank=True, max_length=500)),
                ('points', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('province', models.CharField(blank=True, max_length=500)),
                ('region_1', models.CharField(blank=True, max_length=500)),
                ('region_2', models.CharField(blank=True, max_length=500)),
                ('variety', models.CharField(blank=True, max_length=500)),
                ('winery', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
